# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  before_all do
      @gradle_file = "../app/build.gradle"
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to deploygate"
  lane :alpha do
    gradle(task: "clean assembleDebug")
    branch_name = git_branch
    deploygate(
      api_token: ENV["DEPLOYGATE_API_KEY"],
      user: ENV["DEPLOYGATE_USERNAME"],
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      message: "app updated, from branch \"#{branch_name}\"",
    )
  end

  desc "Deploy a new version to deploygate"
  lane :beta do
    gradle(task: "clean assembleDebug")
    branch_name = git_branch
    deploygate(
      api_token: ENV["DEPLOYGATE_API_KEY"],
      user: ENV["DEPLOYGATE_USERNAME"],
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      message: "app updated, from branch \"#{branch_name}\"",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
